[project]
name = "larzac-org-brebis-emailer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "jinja2>=3.1.6",
    "pillow>=11.2.1",
    "requests>=2.32.4",
]
